version: '3.8'

services:
  web:
    # Вариант 1: Сборка из GitHub (раскомментировать если нужно)
    # build:
    #   context: https://github.com/u71536/playlistchecker.git
    #   dockerfile: Dockerfile
    
    # Вариант 2: Готовый образ из GitHub Container Registry
    image: ghcr.io/u71536/playlistchecker:latest
    
    container_name: playlistchecker-web
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.playlistchecker.rule=Host(`checkingplaylist.com`)"
      - "traefik.http.routers.playlistchecker.entrypoints=websecure"
      - "traefik.http.routers.playlistchecker.tls.certresolver=letsencrypt"
      - "traefik.http.services.playlistchecker.loadbalancer.server.port=5000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: playlistchecker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: playlistchecker
      POSTGRES_USER: playlistchecker
      POSTGRES_PASSWORD: playlistcheckerQp9)3ni~
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-network

volumes:
  postgres_data:

networks:
  traefik-network:
    external: true
