"""Add language field to User model

Revision ID: 5bc04065d00e
Revises: 
Create Date: 2025-10-20 18:44:32.830140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc04065d00e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('browser_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('telegram_username')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('browser_notifications_enabled')
        batch_op.drop_column('telegram_notifications_enabled')
        batch_op.drop_column('email_notifications_enabled')

    op.drop_table('push_subscription')
    # ### end Alembic commands ###
