"""Add track_service_id field to NotificationHistory for unique notification tracking

Revision ID: 82848fa0ea05
Revises: 5bc04065d00e
Create Date: 2025-10-20 20:08:00.721117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82848fa0ea05'
down_revision = '5bc04065d00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_service_id', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_unique_notification', ['user_id', 'playlist_id', 'track_service_id', 'notification_type'], unique=False)
        batch_op.drop_column('date_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_sent', sa.DATE(), nullable=True))
        batch_op.drop_index('idx_unique_notification')
        batch_op.drop_column('track_service_id')

    # ### end Alembic commands ###
